package com.rootscare.ui.physiotherapy.physiotherapycategorylisting

import com.rootscare.ui.base.BaseViewModel
import com.rootscare.ui.nurses.nursescategorylisting.FragmentNursesCategoryListingNavigator

class FragmentPhysiotherapyCategoryListingViewModel: BaseViewModel<FragmentPhysiotherapyCategoryListingNavigator>() {
}