package com.rootscare.ui.babysitter.babysittercategorylisting

import com.rootscare.ui.babysitter.babysitterseealllist.FragmentBabysitterSeeallListingByGridNavigetor
import com.rootscare.ui.base.BaseViewModel

class FragmentBabySitterCategoryListingViewModel: BaseViewModel<FragmentBabySitterCategoryListingNavigator>() {
}