package com.rootscare.ui.physiotherapy.bookingdetails

import com.rootscare.ui.base.BaseViewModel
import com.rootscare.ui.physiotherapy.physiotherapycategorylisting.FragmentPhysiotherapyCategoryListingNavigator

class FragmentPhysiotherapyBookingDetailsViewModel: BaseViewModel<FragmentPhysiotherapyBookingDetailsNavigator>() {
}