package com.rootscare.ui.babysitter.babysitterlistingdetails

import com.rootscare.ui.babysitter.babysittercategorylisting.FragmentBabySitterCategoryListingNavigator
import com.rootscare.ui.base.BaseViewModel

class FragmentBabySitterListingDetailsViewModel: BaseViewModel<FragmentBabySitterListingDetailsNavigator>() {
}